- README.md
- deployment-template/main.tf
- deployment-template/modules/rke/main.tf
- deployment-template/modules/rke/variables.tf
- deployment-template/variables.tf
- rega.py
- setup.py
This PR includes the automated provisioning of OS env vars for the `rke` module. It also updates instructions to make them more user friendly.
> Automation of OS env vars

- Makefile
- rega.py
- setup.py
This PR adds a few missing package dependencies and also implements new functionality in the `rega version` command. Now you can print the rega CLI version.
> Added missing dependencies and QoL updates

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/new-sprint-task.md
- .github/PULL_REQUEST_TEMPLATE.md
1. added `.github` folder with templates from other existing repos
We have an issue on the board that all repositories we use have the same plate, and I noticed this one does not.
> Add Github templates

- Dockerfile
- rega.py
- setup.py
A new subcommand for executing a plan with the accurate configuration settings was created.
1) TF has been updated to 0.12.5
2) New command plan was added
Fixes #18
> Add plan command

- deployment-template/modules/node/main.tf
- deployment-template/modules/rke/main.tf
- setup.py
Remove kubernetes provider and add the RBAC as addon. Bumped version.
Added internal address as recommended here: https://rancher.com/docs/rancher/v2.x/en/installation/ha/kubernetes-rke/
> Remove k8s provider

- rega.py
- setup.py
The aim of this PR is to improve the version management Python packages and images by adding more accurate information when commands are executed.
1) Docker image pulling is now better managed by explicitly adding a new `download_image` method.
2) When creating a new rega environment, a new `.version` file is created containing the version of the Python package used
3) rega version now outputs more detailed information about package and container versions
4) If the user is using a mismatching version of the rega package, a warning message is outputted.
Fixes #22
> Improve docs and version management

- rega/deployment-template/modules/secgroup/main.tf
- rega/deployment-template/modules/secgroup/outputs.tf
- setup.py
Removed security groups that were conflictive with our local deployment. This will improve the overall security of a system deployed with default settings.
1) Both internal UDP and TCP default rules were removed.
> Fix security group issue

- README.md
- rega/cmd.py
- rega/deployment-template/main.j2
- rega/deployment-template/modules/secgroup/main.tf
- rega/deployment-template/modules/secgroup/outputs.tf
- setup.py
Bring back security groups that are relevant to our local deployment. Several tweaks to make deployments compatible with our infrastructure regarding resource manipulation.
1) Now secgroup rules are applied separately to other modules
2) The destroy command has been simplified to comply with more complex infrastructure
> Resource manipulation and security group fixes

- rega/cmd.py
- rega/deployment-template/main.j2
- rega/deployment-template/modules/rke/main.tf
- rega/deployment-template/modules/rke/variables.tf
- setup.py
Remove cluster dependencies of the RKE module in order to make destroy command reliable.
1) RKE cluster deps were removed
2) Destroy command was updated
@viklund
> Remove cluster dependencies of RKE

- rega/cmd.py
- setup.py
Hostvars file generation has been removed from the rega tool, as it is now managed by Terraform.
1) Remove no longer used dependencies
2) Delete hostvar generation function and its calls
Will also fix #39 
Waiting on an external PR  from rega-templates repo
> Remove hostvars file generation

- rega/cmd.py
Length checking does not work with None , so this approach will fix it.
The condition for finding scripts was changed so that the None case is contemplated.
> Fix condition for finding scripts

- rega/cmd.py
The apply command needs to take the target modules in order to work. By
default its suppossed to execute all scripts.
1) The apply command now points to the targeted module(s)
2) Destroy does not take any unused args
> Fix apply command

- setup.py
This version is rather stable after the big refactor
rega package bumped to 1.8.0
> Bump rega version

- rega/cmd.py
The git repositories will be no longer pulled with docker, but with
subprocess. This will ease cloning private repos, among other things.
1) Import subprocess
2) Change the git clone call
@viklund
> Execute git command with subprocess

- Dockerfile
- rega/cmd.py
- setup.py
Image building will be ~4x faster and the size of images halvened. Also, python3 was included in the dependency wheel.
1) Change base image to Alpine
2) Add corresponding changes wrt shell and package installations using `apk`
v1.9.0
> Update Dockerfile to use Alpine

- rega/cmd.py
The container will now mount the top level of the git repository, and the working direcotry is calculated on top of this too.
1) Change volume mount
2) Change wd
> Paths rework

- Dockerfile
Added PyYAML package for python3.
> Add PyYAML dependency

- Dockerfile
- hooks/build
- setup.py
1) Changed docker build command in the dockerhub hook to use a newer tag for caching images
2) Add Jinja2 dependency
3) Bump rega package
> Hook and dependency updates

- Dockerfile
- setup.py
> Add ssh client to rega image

- Dockerfile
- setup.py
> Install bash shell

- rega/cmd.py
- setup.py
> Run only specific types

- rega/cmd.py
- setup.py
Make the k8s related commands work by setting the correct path
1) k8s related paths have been fixed to point at the `cwd`
2) Version check only done in certain commands
> Fix paths and version check
